'use client'

import { useEffect, useState } from 'react'
import { CalendarDays, Check, ChevronDown, Clock3, Heart, MapPin, MessageCircle, Music2, Pause, Play, Volume2, VolumeX } from 'lucide-react'

const WEDDING_DATE = new Date('2026-12-19T17:00:00-03:00')
const WHATSAPP_URL = 'https://wa.me/5585984750154'
const MAPS_URL = 'https://www.google.com/maps/search/?api=1&query=Rua+Fausto+Aguiar+655,+Cambeba'
const photos = {
  cover: '/capa-casamento.png',
  garden: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/WhatsApp%20Image%202026-08-28%20at%2018.13.20%20%283%29-MAP9vioB4BPofYKFoRdcFetAX9G0of.jpeg',
  bridge: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/foto%20cerimomia-Ef7sXD1f7pxKwjcuJY2e4K4WJnliLH.jpeg',
  rings: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/WhatsApp%20Image%202026-08-28%20at%2018.13.20%20%285%29-Au6xkWmWU1ASlngh8mFe4zU3I6YY4g.jpeg',
  sunset: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/imagem%20ultima%20foto-hRYXW5aEY1krJsKEVlS9MgySTas7Ly.jpeg',
}

function Countdown() {
  const [time, setTime] = useState({ days: 0, hours: 0, minutes: 0, seconds: 0 })
  useEffect(() => { const update = () => { const d = Math.max(0, WEDDING_DATE.getTime() - Date.now()); setTime({ days: Math.floor(d / 86400000), hours: Math.floor(d / 3600000 % 24), minutes: Math.floor(d / 60000 % 60), seconds: Math.floor(d / 1000 % 60) }) }; update(); const id = window.setInterval(update, 1000); return () => window.clearInterval(id) }, [])
  return <div className="grid grid-cols-4 gap-3 border-y border-terracotta/20 py-5">{Object.entries(time).map(([label, value]) => <div key={label} className="text-center"><div className="font-serif text-3xl text-terracotta">{String(value).padStart(2, '0')}</div><div className="mt-1 font-sans text-[9px] uppercase tracking-[0.18em] text-ink/55">{label}</div></div>)}</div>
}

function MusicPlayer({ started }: { started: boolean }) {
  const [playing, setPlaying] = useState(false); const [muted, setMuted] = useState(false); const [audio, setAudio] = useState<HTMLAudioElement | null>(null)
  useEffect(() => { const a = new Audio('https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Novo_Amor_-_From_Gold_CeeNaija.com_-mv281Uyk82efQNC8IDnWDQN7fGq9xY.mp3'); a.loop = true; a.volume = .3; setAudio(a); return () => a.pause() }, [])
  useEffect(() => { if (started && audio) audio.play().then(() => setPlaying(true)).catch(() => { }) }, [started, audio])
  return <div className="fixed right-4 top-4 z-30 flex items-center gap-2 rounded-full border border-terracotta/20 bg-cream/90 p-2 shadow-sm backdrop-blur"><Music2 size={14} className="text-terracotta" /><button onClick={() => { if (!audio) return; playing ? audio.pause() : audio.play().catch(() => { }); setPlaying(!playing) }} aria-label={playing ? 'Pausar música' : 'Tocar música'} className="flex size-8 items-center justify-center rounded-full bg-terracotta text-white">{playing ? <Pause size={14} /> : <Play size={14} />}</button><button onClick={() => { if (audio) audio.muted = !muted; setMuted(!muted) }} aria-label={muted ? 'Ativar som' : 'Silenciar música'} className="flex size-8 items-center justify-center text-terracotta">{muted ? <VolumeX size={14} /> : <Volume2 size={14} />}</button></div>
}

function FloralCorner({ className = '' }: { className?: string }) { return <div className={`pointer-events-none absolute text-sage/75 ${className}`} aria-hidden="true"><span className="font-serif text-8xl leading-none">❧</span><span className="absolute -right-3 top-5 text-5xl text-terracotta">✿</span><span className="absolute left-8 top-10 text-3xl text-gold">✿</span></div> }

export default function Page() {
  const [opened, setOpened] = useState(false); const [confirmed, setConfirmed] = useState(false); const [guestName, setGuestName] = useState('')
  const confirm = (event: React.FormEvent) => { event.preventDefault(); if (!guestName.trim()) return; setConfirmed(true); window.open(`${WHATSAPP_URL}?text=${encodeURIComponent(`Olá! Sou ${guestName} e confirmo minha presença no casamento de Lucas e Ariadna.`)}`, '_blank', 'noopener,noreferrer') }
  return <main className="min-h-screen w-full overflow-x-hidden bg-cream text-ink">
    {!opened && <section className="fixed inset-0 z-40 flex items-center justify-center bg-cream px-2 py-2 text-center sm:px-4"><div onClick={() => setOpened(true)} className="relative aspect-[3/4] h-[calc(100svh-1rem)] max-h-[900px] w-full max-w-[680px] cursor-pointer overflow-hidden shadow-xl" role="button" tabIndex={0} aria-label="Abrir convite" onKeyDown={(event) => { if (event.key === 'Enter' || event.key === ' ') setOpened(true) }}><img src={photos.cover} alt="Capa ilustrada do convite de casamento de Lucas e Ariadna" className="absolute inset-0 h-full w-full object-cover" /><button type="button" onClick={(event) => { event.stopPropagation(); setOpened(true) }} aria-label="Abrir convite" className="absolute bottom-[8%] left-1/2 z-10 h-16 w-56 -translate-x-1/2 cursor-pointer rounded-full bg-transparent text-transparent">Abrir convite</button></div></section>}
    <MusicPlayer started={opened} />
    <section className="relative mx-auto max-w-3xl border-x border-gold/30 px-6 py-24 text-center sm:py-36"><FloralCorner className="left-0 top-0" /><FloralCorner className="right-0 top-0 rotate-90" /><p className="font-sans text-xs italic tracking-wide text-ink/60">“Assim, todos verão e saberão, refletirão e entenderão que a mão do Senhor fez isso”</p><p className="mt-2 font-serif text-lg italic text-ink/65">Isaías 41:20</p><div className="mx-auto mt-16 max-w-xl border border-gold/70 p-8 sm:p-16"><p className="font-sans text-xs uppercase tracking-[0.25em] text-terracotta">Nosso grande dia</p><h1 className="mt-8 font-script text-8xl leading-[0.85] text-terracotta sm:text-9xl">Lucas <span className="font-serif text-5xl text-gold">&amp;</span> Ariadna</h1><div className="mx-auto mt-10 h-px w-20 bg-gold/60" /><p className="mt-8 font-serif text-4xl leading-tight text-ink/80 sm:text-5xl">19 de dezembro<br />de 2026</p><p className="mt-3 font-serif text-3xl text-ink/70 sm:text-4xl">às 17 horas</p></div><a href="#convite" className="mx-auto mt-16 flex size-10 items-center justify-center rounded-full border border-terracotta/35 text-terracotta"><ChevronDown size={18} /></a></section>
    <section id="convite" className="relative mx-auto max-w-3xl overflow-hidden border-x border-gold/30 px-6 py-24 text-center sm:py-32"><FloralCorner className="left-0 top-0 -rotate-12" /><FloralCorner className="bottom-0 right-0 rotate-180" /><div className="relative mx-auto max-w-2xl overflow-hidden bg-terracotta px-8 py-14 text-white shadow-sm sm:px-20"><span className="absolute left-4 top-3 font-serif text-5xl text-white/30">❧</span><span className="absolute bottom-1 right-4 rotate-180 font-serif text-5xl text-white/30">❧</span><p className="relative font-serif text-4xl leading-tight sm:text-5xl">O amor nos trouxe até aqui, e queremos celebrar este momento inesquecível ao lado de pessoas especiais.</p></div><img src={photos.garden} alt="Lucas e Ariadna se beijando no jardim" loading="lazy" className="mx-auto mt-12 h-72 w-56 rounded-t-full object-cover object-center sm:h-96 sm:w-72" /></section>
    <section className="relative mx-auto max-w-3xl border-x border-gold/30 px-6 py-24 text-center sm:py-32"><h2 className="font-serif text-5xl text-terracotta sm:text-7xl">Para o grande dia</h2><div className="mx-auto mt-12 grid max-w-xl gap-5 text-left"><div className="flex items-start gap-4 border-b border-olive/15 pb-5"><Heart size={19} className="mt-1 shrink-0 text-terracotta" fill="currentColor" /><p className="font-sans text-sm leading-relaxed text-ink/75">Chegue com 30 minutos de antecedência.</p></div><div className="flex items-start gap-4 border-b border-olive/15 pb-5"><Heart size={19} className="mt-1 shrink-0 text-terracotta" fill="currentColor" /><p className="font-sans text-sm leading-relaxed text-ink/75">Tire muitas fotos e nos ajude a eternizar esse momento.</p></div><div className="flex items-start gap-4"><Heart size={19} className="mt-1 shrink-0 text-terracotta" fill="currentColor" /><p className="font-sans text-sm leading-relaxed text-ink/75">Divirta-se muito!</p></div></div></section>
    <section className="relative mx-auto max-w-3xl border-x border-gold/30 px-6 py-24 text-center sm:py-32"><img src={photos.bridge} alt="Lucas e Ariadna caminhando de mãos dadas" loading="lazy" className="absolute right-0 top-12 h-52 w-36 object-cover opacity-30 sm:h-72 sm:w-52" /><h2 className="font-serif text-6xl text-terracotta sm:text-8xl">Cerimônia</h2><p className="mt-5 font-serif text-2xl text-terracotta/80">Local do evento</p><p className="mt-3 font-sans text-sm italic text-ink/60">19 de dezembro de 2026 · 17h</p><a href={MAPS_URL} target="_blank" rel="noreferrer" aria-label="Abrir o local no Google Maps" className="mx-auto mt-12 flex w-fit items-center gap-4 rounded-full bg-terracotta px-8 py-4 font-serif text-xl text-white transition hover:bg-terracotta/90">Ver mapa <MapPin size={24} /></a><img src={photos.rings} alt="Mãos de Lucas e Ariadna com alianças" loading="lazy" className="mx-auto mt-16 h-52 w-full max-w-lg object-cover opacity-90" /></section>
    <section className="relative mx-auto max-w-3xl border-x border-gold/30 px-6 py-24 text-center sm:py-32"><h2 className="font-serif text-6xl text-terracotta sm:text-8xl">Confirme</h2><p className="mt-3 font-serif text-2xl text-terracotta/80">a sua presença!</p>{confirmed ? <div className="mt-12 flex items-center justify-center gap-2 text-terracotta"><Check size={22} /><span className="font-serif text-xl">Presença confirmada!</span></div> : <form onSubmit={confirm} className="mx-auto mt-10 max-w-sm"><input required value={guestName} onChange={(e) => setGuestName(e.target.value)} placeholder="Seu nome" aria-label="Seu nome" className="h-12 w-full border-b border-terracotta/30 bg-transparent text-center font-sans text-sm outline-none placeholder:text-ink/40" /><button type="submit" aria-label="Confirmar presença pelo WhatsApp" className="mx-auto mt-8 flex min-h-14 items-center gap-3 rounded-full bg-terracotta px-8 py-4 font-sans text-xs uppercase tracking-[0.18em] text-white transition active:scale-95">Confirme sua presença <MessageCircle size={21} /></button></form>}<p className="mx-auto mt-20 max-w-md font-serif text-4xl italic text-terracotta">Te esperamos no altar!</p><img src={photos.sunset} alt="Lucas e Ariadna abraçados ao pôr do sol" loading="lazy" className="mx-auto mt-12 h-80 w-60 rounded-t-full object-cover opacity-90" /></section>
    <footer className="mx-auto max-w-3xl border-x border-t border-gold/30 px-6 py-12 text-center"><Heart size={22} className="mx-auto text-terracotta" fill="currentColor" /><p className="mt-4 font-script text-5xl text-terracotta">Lucas &amp; Ariadna</p><p className="mt-2 font-sans text-[20px] uppercase tracking-[0.25em] text-ink/50">19 / 12 / 2026</p></footer>
  </main>
}
